### ISSUE TITLE
Update group website

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/umd-lhcb.github.io#13]
@manuelfs we probably want to update info on Svende & Christos. Do you want me to do that?

**Comment by manuelfs** [comment]
Yes, thank you. 

At some point we also need to add my last two talks

https://scgp.stonybrook.edu/video/video.php?id=5729

https://indico.fnal.gov/event/58272/timetable/?view=standard#53-lhcb

As well as Phoebe's

https://indico.cern.ch/event/1248281/timetable/#3-overview-of-electronic-and-p

**Comment by yipengsun** [comment]
All done. You can check out the beta version of the website once it is built, then update the official website.

**Comment by manuelfs** [comment]
Thank you very much!

I made some minor updates and pulled it in our server
