### ISSUE TITLE
Continuous Integration (CI) fails (missing cachix) but website can be built locally

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/umd-lhcb.github.io#14]
I had not committed to the website in a long time, but now the CI seems to fails unable to find `cachix`. 

https://github.com/umd-lhcb/umd-lhcb.github.io/actions/runs/5743567913

Running it locally with `jekyll serve` gives no error

```
Annotations
1 error and 2 warnings

tests
Action failed with error: Error: Unable to locate executable file: cachix. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

tests
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, cachix/install-nix-action@v15, cachix/cachix-action@v10. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

tests
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by yipengsun** [comment]
This is because the `cachix-action` fails. In general github actions performs various tasks (e.g. checkout code, install `nix`). Some of them can become outdated because they may use obsolete interfaces thus need updating.

**Comment by yipengsun** [comment]
BTW, `cachix` is used to cache the dev shell (`jekyll`, etc) so we don't need to rebuild `jekyll` itself when we just change the _content_ of the website.

**Comment by manuelfs** [comment]
Is there a solution for this?

**Comment by yipengsun** [comment]
Yes. I've fixed that in my last commit.

**Comment by yipengsun** [comment]
Simple solution: update these outdated actions in https://github.com/umd-lhcb/umd-lhcb.github.io/blob/build/.github/workflows/main.yml

**Comment by manuelfs** [comment]
Thank you!
