### ISSUE TITLE
Add Hassan and Manuel's names to Home page

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/umd-lhcb.github.io#3]
Not sure what the best way to do this. "Professors Jawahery and Franco Sevilla's group"?

**Comment by yipengsun** [comment]
So should I replace 'Our group' -> 'Professors Jawahery and Franco Sevilla's group'?

**Comment by manuelfs** [comment]
There might be better ways, but that's one possibility indeed. Also "Our research group, led by Professors Jawahery and Franco Sevilla, is engaged...". It all sounds a bit pompous to me, but I think it is important to say in front page who the PIs are
