### ISSUE TITLE
Collect public talks given in the last year

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/umd-lhcb.github.io#7]
I believe Phoebe and Manual have given a talk in the last year, also I should collect previous talks from Hassan and update all talks to our website.

**Comment by yipengsun** [comment]
@manuelfs Can you update the talks section by yourself? At least give it a try maybe?

**Comment by manuelfs** [comment]
Sure thing, hopefully this weekend

**Comment by yipengsun** [comment]
@manuelfs I made some changes to the `pages/talks.html` template as well as the `_data/talks.yml` so that the **most recent 9 talks** are automatically generated. 

Please take a look and see if you like it.

**Comment by yipengsun** [comment]
The price we have to pay now is that for every talk entry, the field **author** is now mandatory.
